/**
 * Mock 数据生成器
 * Mock data generator
 */

import type { Emoji, EmojiCollection, EmojiFavorite } from "@/api";

// Mock 表情包数据
export const mockEmojis: Emoji[] = [
  {
    id: "1",
    name: "开心猫咪",
    description: "一只开心的猫咪表情",
    keywords: ["cat", "happy", "cute"],
    category: "动物",
    imageUrl: "https://picsum.photos/200/200?random=1",
    gifUrl: null,
    stickerUrl: null,
    tags: ["可爱", "猫咪", "开心"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "惊讶狗狗",
    description: "一只惊讶的狗狗",
    keywords: ["dog", "surprised", "funny"],
    category: "动物",
    imageUrl: "https://picsum.photos/200/200?random=2",
    gifUrl: null,
    stickerUrl: null,
    tags: ["搞笑", "狗狗", "惊讶"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    name: "点赞手势",
    description: "点赞的手势表情",
    keywords: ["thumbs", "up", "like", "approve"],
    category: "手势",
    imageUrl: "https://picsum.photos/200/200?random=3",
    gifUrl: null,
    stickerUrl: null,
    tags: ["点赞", "手势", "认可"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    name: "庆祝礼花",
    description: "庆祝时的礼花表情",
    keywords: ["celebration", "party", "fireworks"],
    category: "节日",
    imageUrl: "https://picsum.photos/200/200?random=4",
    gifUrl: null,
    stickerUrl: null,
    tags: ["庆祝", "节日", "礼花"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    name: "爱心传递",
    description: "传递爱心的表情",
    keywords: ["love", "heart", "care"],
    category: "情感",
    imageUrl: "https://picsum.photos/200/200?random=5",
    gifUrl: null,
    stickerUrl: null,
    tags: ["爱心", "情感", "温暖"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    name: "笑哭表情",
    description: "笑哭的表情包",
    keywords: ["laugh", "cry", "funny"],
    category: "情感",
    imageUrl: "https://picsum.photos/200/200?random=6",
    gifUrl: null,
    stickerUrl: null,
    tags: ["笑哭", "搞笑", "情感"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    name: "猫咪睡觉",
    description: "一只睡觉的猫咪",
    keywords: ["cat", "sleep", "cute"],
    category: "动物",
    imageUrl: "https://picsum.photos/200/200?random=7",
    gifUrl: null,
    stickerUrl: null,
    tags: ["猫咪", "睡觉", "可爱"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    name: "加油手势",
    description: "加油打气的手势",
    keywords: ["fist", "pump", "encourage"],
    category: "手势",
    imageUrl: "https://picsum.photos/200/200?random=8",
    gifUrl: null,
    stickerUrl: null,
    tags: ["加油", "手势", "鼓励"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "9",
    name: "派对时间",
    description: "派对狂欢表情",
    keywords: ["party", "dance", "music"],
    category: "节日",
    imageUrl: "https://picsum.photos/200/200?random=9",
    gifUrl: null,
    stickerUrl: null,
    tags: ["派对", "狂欢", "音乐"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-09T00:00:00Z",
    updatedAt: "2024-01-09T00:00:00Z",
  },
  {
    id: "10",
    name: "思考人生",
    description: "思考的表情",
    keywords: ["think", "ponder", "confused"],
    category: "情感",
    imageUrl: "https://picsum.photos/200/200?random=10",
    gifUrl: null,
    stickerUrl: null,
    tags: ["思考", "疑惑", "人生"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "11",
    name: "可爱兔子",
    description: "一只可爱的兔子",
    keywords: ["rabbit", "cute", "fluffy"],
    category: "动物",
    imageUrl: "https://picsum.photos/200/200?random=11",
    gifUrl: null,
    stickerUrl: null,
    tags: ["兔子", "可爱", "萌宠"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-11T00:00:00Z",
    updatedAt: "2024-01-11T00:00:00Z",
  },
  {
    id: "12",
    name: "胜利手势",
    description: "胜利V字手势",
    keywords: ["victory", "peace", "success"],
    category: "手势",
    imageUrl: "https://picsum.photos/200/200?random=12",
    gifUrl: null,
    stickerUrl: null,
    tags: ["胜利", "手势", "成功"],
    isPublic: true,
    status: "ENABLED",
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-12T00:00:00Z",
  },
];

// Mock 表情包集合数据
export const mockCollections: EmojiCollection[] = [
  {
    id: "c1",
    name: "萌宠系列",
    description: "可爱的动物表情包集合",
    coverUrl: "https://picsum.photos/400/300?random=101",
    tags: ["动物", "可爱", "萌宠"],
    isFeatured: true,
    sortOrder: 1,
    downloadCount: 1250,
    status: "ENABLED",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    emojis: ["1", "2", "7", "11"],
  },
  {
    id: "c2",
    name: "情感表达",
    description: "各种情感表达的表情包",
    coverUrl: "https://picsum.photos/400/300?random=102",
    tags: ["情感", "表达", "心情"],
    isFeatured: true,
    sortOrder: 2,
    downloadCount: 980,
    status: "ENABLED",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    emojis: ["5", "6", "10"],
  },
  {
    id: "c3",
    name: "手势符号",
    description: "常用手势表情包",
    coverUrl: "https://picsum.photos/400/300?random=103",
    tags: ["手势", "符号", "表达"],
    isFeatured: false,
    sortOrder: 3,
    downloadCount: 756,
    status: "ENABLED",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    emojis: ["3", "8", "12"],
  },
  {
    id: "c4",
    name: "节日庆典",
    description: "节日庆祝主题表情包",
    coverUrl: "https://picsum.photos/400/300?random=104",
    tags: ["节日", "庆祝", "派对"],
    isFeatured: true,
    sortOrder: 4,
    downloadCount: 1520,
    status: "ENABLED",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    emojis: ["4", "9"],
  },
];

// Mock 收藏数据
export const mockFavorites: EmojiFavorite[] = [
  {
    id: "f1",
    userId: "user-1",
    emojiId: "1",
    emoji: mockEmojis[0],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "f2",
    userId: "user-1",
    emojiId: "5",
    emoji: mockEmojis[4],
    createdAt: "2024-01-02T00:00:00Z",
  },
];

// 所有可用的标签
export const mockTags = [
  "可爱", "猫咪", "开心",
  "搞笑", "狗狗", "惊讶",
  "点赞", "手势", "认可",
  "庆祝", "节日", "礼花",
  "爱心", "情感", "温暖",
  "笑哭", "思考", "疑惑",
  "睡觉", "兔子", "萌宠",
  "加油", "鼓励", "胜利",
  "派对", "狂欢", "音乐",
  "人生", "成功",
];

// 所有可用的分类
export const mockCategories = [
  "动物",
  "手势",
  "节日",
  "情感",
];
